name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for more advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using secrets
      # IMPORTANT: You must create DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets in your repository settings.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the image and push it to Docker Hub
      # The image will be tagged with 'latest' and a timestamp.
      # The image name is dynamically generated from your GitHub username and repository name.
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nimfer/auto-round:latest
          # Example tag: your-github-username/your-repo-name:latest
